language: node_js
node_js:
  - '8'
branches:
  only:
    - master
after_success:
  - npm run coverage
  - typedoc --out docs ./src
deploy:
  provider: pages
  target_branch: gh-pages
  skip_cleanup: true
  local_dir: docs
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: FZZyVpv4n9s798LZTXMCm4sralanXVP590e2Vfdd0dWEyrKoweePIPS547sqmZpv3bA1N9IvtBaPeJYloTcFSNhB7DsGxiWfzAyBPz/n4+v6+3eTakSjxvgOVqXfOBGRiAxBbjilq+OvA+h63Bdx3TfkJf0B4yxR2/uWn06vWwKdwP5zZmC1Mssylq+WSl1fHXcmW/hNuMaTxy8g9XrLmPbwm3qRDuUDqkAmhs1YDRrrOHSx0s/gZIUpDShaiSIKdpxpi6q/Wn40l5rtPDnX1nmmMZ0X04xXXhy2RzxqMX0zcTXW4kofwT3samekSEkM0FhsCax9HS5Xsw/neV6FAhJSUlGGarm+3kKsGT7PX2aZK/D7sSr5QJ2RsqbLYhdQ3dIiISCqQeWN6UOPTxzbNZqtqetz7Y01RXsckl9mZr01vvXyHbRmfsuVmz3zASpTnMMx8OeZc9dDmpQr+WX1TbmU6IsYk9361bu8rmMo3TvL4k+TZQjB6l8cDdEa6laJQDrBhqsXp/+Ih5wwQyvd9qtOEhgZfSce22xp3Syd1K4+4EuLAydJdB5m/85t8E8Y1lH7TnQ0tjlZISqVQFwBh/AQ0rqadPYM/cvPNa0XpO0ClnKZv78jRtyKh1QaHTKJxBbETEX10hxeK5bhHjAYnvCudpFB1XnxT99L6s++UEM=
