language: node_js
node_js:
  - '8'
branches:
  only:
    - master

after_success:
  - npm run coverage
  - npm run doc

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
