language: node_js
node_js:
  - '8'
branches:
  only:
    - master
env:
  global:
    secure: vh+QN8Q0gXqqoS5hZBUssvO4lcDW6a0E8yfKnC1f4vRC+/wzb8mvLPnr8dniUiSzvNWyg6ET5elLAQWG17pkNw7LwfpBBBCa9EfUPrMdpYdYnLDd3jCtcRIhkvJsCe7xvLJgLSDAW5hkNPw+kG2AxJvmcOppP+IySPdrP5f0TbWGiEvr+0VUZrhdkt0vyv1TH9trI1EbMUUZVkYTblTo9hnfJS47EUnzb5qCq4Fb6M9GCsUKNFqsgDbachc1V8Hu7rok+8gwrovLhQYdFULVkeF7wTZUOahm2Kqkv7AQFSi36J1eVSPHx6q8W3uvvApKyVyHcB1TwwzBwiOSWlGEnZE6rm9t6nKcRH3/T7ZeTixwmKzOsEdMIFdRJXMehYzJPbGVVaYONo5dHUs+Ej1cKe4CpG5RL1cQ+4bY6KjhnHi7Qu0K2gzHgFtL8aAkqOiuZlwyvr3JZdAtvv+PLXuaYfUmSehjXguf3B27emOcSU2lliUQG9BZAY4TvtkKPUYTuQXEg4hcP3wLB/2ECNZ5Ui2S6vx/3G7TyGVxeLIa4Z7l5w2E1P4dFo/9GVvCNRYQreBuX2IlHzexkrq59voJTt8yFrEyzfK84/55RBTMC5jnKPye/qaWjqIoH2+f1uNw5GHdItilZ0wpPRnMV5atMo2B3XFvmF10o0CxiEhup3o=

after_success:
  - npm run coverage
  - typedoc --out docs ./src
deploy:
  provider: pages
  target_branch: gh-pages
  skip_cleanup: true
  local_dir: docs
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
